services:
  octopus:
    image: ghcr.io/vrichv/octopus-pro
    ports:
       - '8080:8080'
    volumes:      
       - '/path/to/data:/app/data'
    container_name: octopus
    restart: unless-stopped